# .github/workflows/node.js.yaml

# This workflow will do a clean install of node dependencies, build the source
# code and run tests across different versions of node on ubuntu, macos and
# windows.
# https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.runs-on }}

    strategy:
      matrix:
        runs-on: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [10.x, 12.x, 14.x, 15.x]
        # See https://nodejs.org/en/about/releases/.

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }} on ${{ matrix.runs-on }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run ci
